// Code generated by Slice Machine. DO NOT EDIT.

import Circle from './Circle/index.svelte';
import Contact from './Contact/index.svelte';
import Documentation from './Documentation/index.svelte';
import FeatureList from './FeatureList/index.svelte';
import Input from './Input/index.svelte';
import RichText from './RichText/index.svelte';
import Spacer from './Spacer/index.svelte';
import TextList from './TextList/index.svelte';
import Video from './Video/index.svelte';
import Wheel from './Wheel/index.svelte';

export const components = {
	circle: Circle,
	contact: Contact,
	documentation: Documentation,
	feature_list: FeatureList,
	input: Input,
	rich_text: RichText,
	spacer: Spacer,
	text_list: TextList,
	video: Video,
	wheel: Wheel
};
