// Code generated by Slice Machine. DO NOT EDIT.

import AboutContent from './AboutContent/index.svelte';
import AboutOpener from './AboutOpener/index.svelte';
import Circle from './Circle/index.svelte';
import ClientsAndCollaborators from './ClientsAndCollaborators/index.svelte';
import Contact from './Contact/index.svelte';
import ContactMedia from './ContactMedia/index.svelte';
import ContactUsHeader from './ContactUsHeader/index.svelte';
import Conversation from './Conversation/index.svelte';
import Documentation from './Documentation/index.svelte';
import FeatureList from './FeatureList/index.svelte';
import Input from './Input/index.svelte';
import List from './List/index.svelte';
import Logo from './Logo/index.svelte';
import MediaAndCircle from './MediaAndCircle/index.svelte';
import MediaMedia from './MediaMedia/index.svelte';
import MediaMultiple from './MediaMultiple/index.svelte';
import RichText from './RichText/index.svelte';
import Spacer from './Spacer/index.svelte';
import TagCloud from './TagCloud/index.svelte';
import TextList from './TextList/index.svelte';
import Video from './Video/index.svelte';
import VideoAndGenerator from './VideoAndGenerator/index.svelte';
import VideoAndGeneratorMultiple from './VideoAndGeneratorMultiple/index.svelte';
import VideoAutoplay from './VideoAutoplay/index.svelte';
import Wheel from './Wheel/index.svelte';

export const components = {
	about_content: AboutContent,
	about_opener: AboutOpener,
	circle: Circle,
	clients_and_collaborators: ClientsAndCollaborators,
	contact: Contact,
	contact_media: ContactMedia,
	contact_us_header: ContactUsHeader,
	conversation: Conversation,
	documentation: Documentation,
	feature_list: FeatureList,
	input: Input,
	list: List,
	logo: Logo,
	media_and_circle: MediaAndCircle,
	media_media: MediaMedia,
	media_multiple: MediaMultiple,
	rich_text: RichText,
	spacer: Spacer,
	tag_cloud: TagCloud,
	text_list: TextList,
	video: Video,
	video_and_generator: VideoAndGenerator,
	video_and_generator_multiple: VideoAndGeneratorMultiple,
	video_autoplay: VideoAutoplay,
	wheel: Wheel
};
